config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  mount RailsAdmin::Engine => '//admin', as: 'rails_admin'
  root 'home#index'
  resources :home, only: [:index] do
    collection do
      post 'mailchimp'
    end
  end

  resources :contact, only: [:index, :create]
  resources :wishlist, only: [:index, :create, :destroy]

  
  get "welcome/index"
  get "welcome/blog"
  get "welcome/blog_single"
  
  get "welcome/cart"
  get "welcome/checkout"
  get "welcome/contact"
  post "welcome/contact_us"

  get "welcome/login"
  get "welcome/order", to: 'welcome#order'
  get "products/show"

  # post 'home/mailchimp', to:'home#mailchimp', as: 'mailchimp'

  get 'welcome/product_details/:id', to: 'welcome#product_details', as: 'product_details'
  post 'welcome/create',to: 'welcome#create'
  get 'welcome/success', to: 'welcome#success', as: "shop_success"
  post 'welcome/create',to: 'welcome#create'

  get "welcome/stripe", to: "welcome#stripe"
  get "welcome/track"
  post "welcome/track"
  get 'welcome/cod'
  get 'welcome/checkout_product', to: "welcome#checkout_product"
  
  post "welcome/cart"
  post "profile/update", to: "profile#update", as: "profile_update"
  get "welcome/myaccount"
  get "welcome/shop"
  get "welcome/error404"
  resources :categories
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  delete 'products/remove_product/:id', to: "products#remove_product", as: "remove_product"

  post '/new/:id', to: "user_wish_list#new", as: "new"
  # delete "user_wish_list/remove_wishlist/:id", to:  "user_wish_list#remove_wishlist", as: "remove_wishlist"
  # get'products/wishlist'

  post 'products/:id/add' => "products#add_quantity", as: "add_quantity"
  post 'products/:id/minus' => "products#dec_quantity", as: "dec_quantity"
  
  # Defines the root path route ("/")
  # root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require "MailchimpMarketing"
  skip_before_action :authenticate_user!
  def index
    @feature_products = Product.all rescue nil 
    @category = Category.where(parent_id: nil)  
    @baner = Baner.all
    @cms = Cm.all
  end

  def mailchimp
    mailchimp = MailchimpMarketing::Client.new()
    mailchimp.set_config({
      :api_key => "c8653bb20730e6d2db806ec1554c0a27",
      :server => "us13"                  
    })
    list_id = "cdd89c9809"               
    response = mailchimp.lists.add_list_member list_id, {
      email_address: params[:email],
      status: "subscribed",
      merge_fields:{
        FNAME: params[:fname],
        LNAME: params[:lname],
        ADDRESS: {
          addr1: params[:addr1],
          city: params[:city],
          state: params[:state],
          zip: params[:zip],
        },
      },
    }
  # flash.now[:notice] = "Subscribed"
  # rescue MailchimpMarketing::ApiError => e
  # flash[:notice] = "user already exists"
  # puts "Error: #{e}"

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
	
	<section id="slider"><!--slider-->
		<div class="container fix">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>
						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free E-Commerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
								</div>
								<div class="col-sm-6">
									<% @baner.each do |baner| %>
								<% if baner.image.attached? %>
									<img src="<%= url_for(baner.image) %>">
									<% end %>
								<% end %>      
									<%= image_tag("home/pricing.png" ,class: "pricing", alt: "") %>
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>100% Responsive Design</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<%= image_tag("home/girl2.jpg", alt: "like", class: "girl img-responsive") %>
									<%# <img src="images/home/girl2.jpg" class="girl img-responsive" alt="" /> %>
									<%= image_tag("home/pricing.png", alt: "", class: "pricing") %>
									<%# <img src="images/home/pricing.png"  class="pricing" alt="" /> %>
								</div>
							</div>
							
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free Ecommerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<%= image_tag("home/girl3.jpg", alt: "", class: "girl img-responsive") %>
									<%# <img src="images/home/girl3.jpg" class="girl img-responsive" alt="" /> %>
									<%= image_tag("home/pricing.png", alt: "", class: "pricing") %>
									<%# <img src="images/home/pricing.png" class="pricing" alt="" /> %>
								</div>
							</div>
							
						</div>
						
						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>
					
				</div>
			</div>
		</div>
	</section><!--/slider-->
	
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<% @category.each do |category| %>
						<% subcatagories = category.subcategories%>
						<div class="panel-group category-products" id="accordian" style="margin-top: 30px;"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h6 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#<%= category.id%>">
											<span class="badge pull-right"><i class="fa fa-caret-square-o-down" style="font-size:24px"></i></i></span>
											<h2><%= category.name %></h2>
										</a>
									</h6>
								</div>
							</div>
							<div id="<%= category.id%>" class="panel-collapse collapse">
								<div class="panel-body">
									<% subcatagories.each do |subcat| %>
									<i style="margin-left: 58px;"><%= link_to subcat.name, product_details_path(subcat) %></i>
									<%# <a href=""><%= subcat.subcat_name %>
									<% end %>
								</div>
							</div>
					
						</div><!--/category-products-->	
						<%end%>			
					</div>
				</div>
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>
						<% @feature_products.each do |product| %>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<% if product.image.attached? %>
												<%#= link_to product_path(product) do%><img src="<%= url_for(product.image) %> "style="height: 180px; width: 200px;" >
											<% end %>
											<h2>USD $<%= product.price %></h2>
											<p><%= product.name %></p>
											<p><%= product.short_description %></p>
											<p><%= product.long_description %></p>
											<div style="display:flex;">
											
                        <div style="margin-left: 32px">
                          <%= button_to add_to_cart_path(product) do %>
                            <i class="fa fa-shopping-cart" style="font-size:25px"></i>
                          <% end %>
                        </div>	
                        
                        <div style="margin-left: 98px;">
                          <%= button_to wishlist_index_path(id: product) do %>
                            <i class="fa fa-heart-o" style="font-size:25px;color:red"></i>
                          <% end %>
                        </div>			
                    </div>    
                  </div>
								</div>

							</div>

						</div>
						<%end%>
              <button style="margin-top:330px;background-color: orange;position: absolute;"><%= link_to ">>", products_show_path %></button>
            
					</div><!--features_items-->
				</div>
			</div>
		</div>
  
	</section>