config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  mount RailsAdmin::Engine => '//admin', as: 'rails_admin'
  root 'home#index'
  resources :home, only: [:index] do
    collection do
      post 'mailchimp'
    end
  end

  resources :contact, only: [:index, :create]
  resources :wishlist, only: [:index, :create, :destroy]

  
  get "welcome/index"
  get "welcome/blog"
  get "welcome/blog_single"
  
  get "welcome/cart"
  get "welcome/checkout"
  get "welcome/contact"
  post "welcome/contact_us"

  get "welcome/login"
  get "welcome/order", to: 'welcome#order'
  get "products/show"

  # post 'home/mailchimp', to:'home#mailchimp', as: 'mailchimp'

  get 'welcome/product_details/:id', to: 'welcome#product_details', as: 'product_details'
  post 'welcome/create',to: 'welcome#create'
  get 'welcome/success', to: 'welcome#success', as: "shop_success"
  post 'welcome/create',to: 'welcome#create'

  get "welcome/stripe", to: "welcome#stripe"
  get "welcome/track"
  post "welcome/track"
  get 'welcome/cod'
  get 'welcome/checkout_product', to: "welcome#checkout_product"
  
  post "welcome/cart"
  post "profile/update", to: "profile#update", as: "profile_update"
  get "welcome/myaccount"
  get "welcome/shop"
  get "welcome/error404"
  resources :categories
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  delete 'products/remove_product/:id', to: "products#remove_product", as: "remove_product"

  post '/new/:id', to: "user_wish_list#new", as: "new"
  # delete "user_wish_list/remove_wishlist/:id", to:  "user_wish_list#remove_wishlist", as: "remove_wishlist"
  # get'products/wishlist'

  post 'products/:id/add' => "products#add_quantity", as: "add_quantity"
  post 'products/:id/minus' => "products#dec_quantity", as: "dec_quantity"
  
  # Defines the root path route ("/")
  # root "home#index"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
@@f_value = 0
before_action :authenticate_user! , except: [:index]

  def index
    @feature_products = Product.all rescue nil 
    @category = Category.where(parent_id: nil)  
    @baner = Baner.all
    @cms = Cm.all
  end    

  def create
    @address = current_user.addresses.new(address_params)
    if @address.save
      flash[:success] = "address created successfully!"
      redirect_to welcome_checkout_path
    else
      flash.now[:error] = "address not created"
      render "welcome/checkout"
    end
  end

  def blog
    a = UserOrder.last
    if a.destroy
      flash[:success] = "record deleted"
      redirect_to welcome_blog_path
    else
      puts "-----------------------#{a.errors.full_messages}-------------------------"
    end
  end
  
  def blog_single
  end

  def myaccount
  end  
  
  def cart
    product = Product.all
    @product_price = [] 
    @cart.each do |product| 
      temp = (product.quantity)*(product.price)
      @product_price << temp
    end
    @value = @product_price.inject {|sum,price| sum + price}  
    @value =  @value.to_i
    if @value < 500 && @value > 0
      @shipping_cost = 50
    else
      @shipping_cost = 0
    end
    @final_value = @value + @shipping_cost 
    @user = current_user
    
    user_c = UserCoupon.find_by(coupon_code: params[:coupon_code])
      if params[:coupon_code].nil?
        @f_value = @final_value
        @@f_value = @final_value
      elsif user_c.nil?        
        flash.now[:notice] = "Coupon invalid"
      elsif @user.user_coupons.include?(user_c)
        flash.now[:notice] = "already applied!"
        # binding.pry
      else
        user_c.no_of_uses += 1
        @user.user_coupons << user_c
        @f_value = @final_value - (@final_value*(user_c.percent_off)/100)
        @@f_value = @f_value
        flash.now[:notice] = "Coupon applied successfully!"
      end
    end

  def stripe
    product=Stripe::Product.create({name: 'Order 1'})
    Stripe::Price.create({
    unit_amount: @@f_value,
    currency: 'usd',
    product: product.id,
    })
      @session = Stripe::Checkout::Session.create({
        payment_method_types: ['card'],
        line_items: [
        price_data: {
        product: product.id,
        unit_amount: @@f_value*100,
        currency: 'usd'
      },
      quantity: 1,
      ],
      mode: 'payment',
      success_url: 'http://localhost:3000/welcome/success?true&session_id={CHECKOUT_SESSION_ID}',
      cancel_url: root_url,
      })
    end
  
    def checkout
      @address = current_user.addresses.last
    end

    def checkout_product
      amount = @@f_value
      product_price_lists = [] 	
      products = Product.where(id: @cart.map(&:id))
      if @@trans == 1
        payment_gateway = "COD"
        trans_id = 1
      else
        payment_gateway = "Stripe"
        trans_id = @@trans
      end

      addresses = current_user.addresses.last
      # binding.pry
      order = UserOrder.create(user_id: current_user.id,address_id: addresses.id, grand_total: amount,payment_gateway_id: payment_gateway, transaction_id: trans_id )
      if order.save
        products.each do |product|
          order.order_details.create(product_id: product.id, amount:product.price, quantity: product.quantity)
          total = (product.quantity)*(product.price)
          product_price_lists << total
          product.quantity = 1
          product.save
        end
      else
        UserMailer.send_order_details(current_user,order).deliver
        UserMailer.send_order_details_admin(current_user,order).deliver
      end
    end
  
  
  def cod
    @@trans = 1
    checkout_product
    @value = @@f_value
    session[:cart] = nil
  end  
    
  def login
  end

  def track
    order = current_user.user_orders.all
    id = params[:user_order_id].to_i
		if (order.ids).include?(id) 
      @user_order = UserOrder.find_by(id: id)
    elsif id != 0 && (order.ids).include?(id) == false  #if we convert nil to integer we get 0 so wrote 0 instead of nil
      flash[:alert] = "incorrect order id"
    end
  end  

  def order
    @orders = current_user.user_orders.all 
    # binding.pry
  end  
  
  def product_details
    @category = Category.find(params[:id]) 
    @products = @category.products
  end
  
  def success
    response = Stripe::Checkout::Session.retrieve(id: params[:session_id])
    @trans_id = response[:payment_intent]
    @@trans = @trans_id
    payable_amt = response[:amount_total]
    @total_amt = payable_amt/100
    amount= payable_amt/100
    @pay_response = current_user.payment_responses.create(transaction_id: response[:payment_intent], amount: amount)
    checkout_product
    @products = Product.all
    session[:cart] = nil
  end

  def shop
  end
  
  def error404
  end    

  def catprods
    @cms = Cm.all
    @category = Category.all
  end

  private
  def address_params
    params.permit(:address_1,:pincode, :mobile_no, :country, :city, :state)
  end
  #require(:address)
  def contact_params
		params.require(:contact_u).permit(:name,:email,:contact_no,:message)
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/cart.html.erb
<section class="fix">
<% if @cart.product.present? %>
	<section id="cart_items">
		<div class="container">
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
          <% @cart.each do |product| %>
            <tbody>
              <tr>
                <td class="cart_product">
                  <% if product.image.attached? %>
                    <img src="<%= url_for(product.image)%>" style="height: 80px; width: 70px;">
                    <% end %>
                    <h3><%= product.name %></h3>
                </td>
                <td class="cart_description">
                  <p>Description: <%= product.short_description %></p>
                  <%# <p>SKU NO.</p> %>
                <p>SKU no. : <%= product.sku %></p>
                </td>
                <td class="cart_price">
                  <p>US$ <%= product.price %></p>
                </td>
                <td class="cart_quantity">
                  <div class="cart_quantity_button">
				  <div style="display:flex;" >
                    <%= button_to '+', add_quantity_path(product) , method: :post, data: { turbo: true} %>                  
                    <span style="padding: 5px;">  <%= product.quantity %>  </span>
                    <%= button_to '-', dec_quantity_path(product), method: :post, data: { turbo: true, confirm: "Are you sure you want to delete this?"} %>
                  </div>
				  </div>
                </td>
                <td class="cart_total">
                   <p>US$ <%= (product.price) * (product.quantity) %></p>
                </td>
                <td class="cart_delete">
					      <%= button_to "X", remove_from_cart_path(product), method: :delete %>
                  <%# <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a> %>
                </td>
              </tr>
            </tbody>
          <% end %>
				</table> 
			</div>
		</div>
	</section> <!--/#cart_items-->

	<section id="do_action">
		<div class="container">
			<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="chose_area">
						<ul class="user_option">
							<li>
								<%= form_with model: @coupon, url: welcome_cart_path,  local: true,data: { turbo: false } do |form| %>
									<ul class="user_option">
										<li>
											<div class="mb-3">
												<%= form.label :coupon_code %>
												<%= form.text_field :coupon_code,required: true, class: "form-control" , placeholder: "enter coupon code" %>
											</div>
										</li>
										<li>
											<div class="mb-3">
												<%= form.submit "Apply", class: "btn btn-primary" %>
											</div>
                    					</li>
									</ul>
								<% end %>
							</li>
						</ul>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="total_area">
						<ul>
							<li>Cart Sub Total <span><%= @value %></span><span> US$</span></li>
							<% if  @shipping_cost.present? %>
								<li>Shipping Cost <span><%= @shipping_cost %></span><span> US$</span></li>
							<%end%>
							<% if @f_value.present? %>
								<li>Total <span><%= @f_value %></span><span>US$<span>
							<% else %>
								<li>Total <span><%= @final_value %></span><span>US$<span>
							<% end %>
						</ul>
						<%if @f_value == 0 %>
							<br><h6 style="color:red"><%= "No products in the cart" %></h6>
						<%else%>
							<span class="btn btn-default check_out" href=""><%= link_to "Checkout", welcome_checkout_path %> </span>
						<%end%>
						<%# <a href="checkout.html", style="padding: 40px;"><i class="fa fa-shopping-cart"></i> Checkout</a> %>
					</div>
				</div>
			</div>
		</div>
	</section><!--/#do_action-->
<% else %>
	<div style="padding-left: 23%;">
	<%= image_tag("home/empty_cart1.png", alt: "", class: "girl img-responsive") %>
	</div>
<% end %>
	
</section>

  

app/views/welcome/catprods.html.erb
<h1>Subcategaries</h1>

app/views/welcome/cod.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<body>
<div class="container fix">
  <article>
    <div class="row text-center">
      <div class="col-sm-6 col-sm-offset-3">
      <br><br> <h2 style="color:#0fad00">Success</h2>
      <%= current_user.email%>
      <h1>Order has been placed thank you for shopping with Eshopper</h1>
      <%# <h3>Transaction id: <%=  @trans_id</h3>  %>
      <h3>Amount: USD $<%= @value %></h3>
      <%= link_to "Continue shopping", root_path %>
      <br><br>
      <% @cart.each do |product| %>
        <tbody>
          <tr>
            <td class="cart_product">
              <% if product.image.attached? %>
                <img src="<%= url_for(product.image) %>">
                <% end %>
                <h3><%= product.name %></h3>
            </td>
                <td class="cart_description">
                  <p>Description: <%= product.short_description %></p>
                </td>  
      <% end %>  
      </div>
	  </div>
  </article>
</div>

</body>
</html>

app/views/welcome/contact.html.erb
	
<div class="container-fluid fix">
  <div class="row">
    <div class="col-md-4" style="margin-bottom: 88px;">
      <%= image_tag("shop/cont.jpeg", alt: "contact us") %>
    </div>
    
    <div class="col-md-3">
			<%= form_with model: @contact, url: welcome_contact_us_path,method: :post, data: {turbo: false} do |form| %>
        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |msg| %>
              <div><%= msg %></div>
            <% end %>
          </div>
        <% end %>


        <div class="field">
					<%= form.text_field :name, class:"form-control",placeholder:"Name", value: ""%><br>
          <%= form.text_field :email, class:"form-control",placeholder:"Email" %><br>
			    <%= form.number_field :contact_no, class:"form-control",placeholder:"Contact Number", pattern: "[1-9]{1}[0-9]{9}" %><br>
          <%= form.text_area :message, class:"form-control",placeholder:"Write msg to admin" %>
					
					<div class="btn btn-primary">
    			<%= form.submit "send" %>
  				</div>
        </div><br><br>
			<% end %>
    </div>  
    <div class="col-md-4">
      <div class="title text-center">
      <% if @cont.present? %>
        <b style="color:red;">Reply from admin to you: <i><%= @cont.note_admin %> </b></i>
      <%end %>
      </div>  
    </div>
  </div>
</div>

app/views/welcome/error404.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/price-range.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
	<link href="css/main.css" rel="stylesheet">
	<link href="css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	<div class="container text-center">
		<div class="logo-404">
			<a href="index.html"><img src="images/home/logo.png" alt="" /></a>
		</div>
		<div class="content-404">
			<img src="images/404/404.png" class="img-responsive" alt="" />
			<h1><b>OPPS!</b> We Couldn’t Find this Page</h1>
			<p>Uh... So it looks like you brock something. The page you are looking for has up and Vanished.</p>
			<h2><a href="index.html">Bring me back Home</a></h2>
		</div>
	</div>

  
    <script src="js/jquery.js"></script>
	<script src="js/price-range.js"></script>
    <script src="js/jquery.scrollUp.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/main.js"></script>
</body>
</html>

app/views/welcome/myaccount.html.erb
<div class="updateprofile fix">
  <h1 id="l" style=" padding: 14px; padding-left: 35px;"> Edit Account</h1>
  <%= form_with model: @users, url: profile_update_path,method: :post, local: true do |form| %>
    
  <% if user_signed_in? %>
      <% user = current_user %>
      <b>First Name</b><%= form.text_field :first_name, type: "text",title: "only letters are allowed", pattern: "[A-Za-z]{1,32}",required: true, class: 'form-control', value:user.first_name %>
      <b>Last Name</b><%= form.text_field :last_name,type: "text",title: "only letters are allowed", pattern: "[A-Za-z]{1,32}", required: true, class: 'form-control', value:user.last_name %>
      <b>Mobile no.</b><%= form.text_field :mobile_number, type: "text",pattern: "[1-9]{1}[0-9]{9}",title: "Enter 10 digits valid mobile no.", required: true, class: 'form-control', value:user.mobile_number %>
      <b>Email</b><%= form.text_field :email, type: "text", pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$", required: true, class: 'form-control', value:user.email %></li>
      <% end %><br>
      <div class="actions">
        <%= form.submit value = "UPDATE" %>
      </div>
  <%end%>
</div>

<div class="grouping_button">
  <div class="btn-group">
    <button id="l"><%= link_to "Change password", edit_user_registration_path %></button>
    <button id="l"><%= link_to "Track order", welcome_track_path %></button>
    <button id="l"><%= link_to "My order ", welcome_order_path %></button>
  </div>
</div>

app/views/welcome/order.html.erb
<div class="container fix">
  <%if @orders.present? %>

    <section id="cart_items">
        <div class="table-responsive cart_info">
          <table class="table table-condensed">
            <thead>
              <tr class="cart_menu">
                <td class="image">Product image</td>
                <td class="description">Product name</td>
                <td class="price">Price</td>
                <td class="price">Quantity</td>
                <td class="price">Order id</td>
              </tr>
            </thead>
            <%# @cart.each do |product| %>
            <% @orders.each do |order| %>
              <% order.products.each do |product| %>
                <% od = OrderDetail.all%>
                <% order_d = od.find_by(user_order_id: order.id)%>
                <tbody>
                  <tr>
                    <td class="cart_product">
                      <img src="<%= url_for(product.image) %>"style="height: 80px; width: 70px;">
                    </td>
                    <td class="cart_description">
                    <b><%= product.name %><b>
                    </td>
                    <td class="cart_price">
                    <b>USD $<%= product.price %><b>
                    </td>
                    <td class="cart_price">
                    <b><%= order_d.quantity %></b>
                    </td>
                    <td class="cart_price">
                      <b>ID: <%= order.id %></b>
                    </td>
                  </tr>
                </tbody>
              <% end %>
            <% end %>  
          </table> 
        </div>
        <% else %>
          <div style="padding-left: 23%;">
            <%= image_tag("home/empty_cart1.png", alt: "", class: "girl img-responsive") %>
          </div>
      <% end %>
    </div>
	</section> <!--/#cart_items-->

app/views/welcome/product_details.html.erb
	<section>
		<div class="container fix">
			<div class="row">
				
				
				<div class="col-sm-9 padding-right">
					<div class="product_details"><!--product_details-->
						<div class="col-sm-5">
							<% @products.each do |product| %>
							<div class="view-product">
								<%= image_tag product.image %>
								<%# <img src="images/product_details/1.jpg" alt="" /> %>
							</div>
							
							
						</div>
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<%= image_tag("product_details/new.jpg",class: "newarrival", alt: "like") %>
								<%# <img src="images/product_details/new.jpg" class="newarrival" alt="" /> %>
								<h2><%= product.name %></h2>
								<p>Description: <%= product.short_description%></p>
								<%= image_tag("product_details/rating.png", alt: "like") %>
								<%# <img src="images/product_details/rating.png" alt="" /> %>
								<span>
									
									<span style="margin-left: -88px;">US$ <%= product.price%></span>
									
									<%# <div style="display:flex;"> %>
										
								<div class="inline-block">
									<%= button_to add_to_cart_path(product) do %>
										<i class="fa fa-shopping-cart" style="font-size:25px"></i>
									<% end %>
									<%= button_to wishlist_index_path(id: product) do %>
										<i class="fa fa-heart-o" style="font-size:25px;color:red"></i>
									<% end %>
								</div>
								</span>
								<p><b>Availability:</b> In Stock</p>
								<p><b>Condition:</b> New</p>
								<p><b>Brand:</b> E-SHOPPER</p>
								<a href=""><%= image_tag("product_details/share.png",class: "share img-responsive", alt: "like") %></a>
							</div><!--/product-information-->
						</div>
					</div><!--/product_details-->
					<% end %>
					<div class="category-tab shop-details-tab"><!--category-tab-->
						
						<div class="tab-content">
							<div class="tab-pane fade" id="details" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery1.jpg", alt: "like") %>
												<%# <img src="images/home/gallery1.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery2.jpg", alt: "like") %>
												<%# <img src="images/home/gallery2.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery3.jpg", alt: "like") %>
												<%# <img src="images/home/gallery3.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery4.jpg", alt: "like") %>
												<%# <img src="images/home/gallery4.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="tab-pane fade" id="companyprofile" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery1.jpg", alt: "like") %>
												<%# <img src="images/home/gallery1.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery3.jpg", alt: "like") %>
												<%# <img src="images/home/gallery3.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery2.jpg", alt: "like") %>
												<%# <img src="images/home/gallery2.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery4.jpg", alt: "like") %>
												<%# <img src="images/home/gallery4.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="tab-pane fade" id="tag" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery1.jpg", alt: "like") %>
												<%# <img src="images/home/gallery1.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery2.jpg", alt: "like") %>
												<%# <img src="images/home/gallery2.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery3.jpg", alt: "like") %>
												<%# <img src="images/home/gallery3.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<%= image_tag("home/gallery4.jpg", alt: "like") %>
												<%# <img src="images/home/gallery4.jpg" alt="" /> %>
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							
						</div>
					</div><!--/category-tab-->
					
					
					
				</div>
			</div>
		</div>
	</section>
	
	
</body>
</html>