config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  mount RailsAdmin::Engine => '//admin', as: 'rails_admin'
  root 'home#index'
  resources :home, only: [:index] do
    collection do
      post 'mailchimp'
    end
  end

  resources :contact, only: [:index, :create]
  resources :wishlist, only: [:index, :create, :destroy]

  
  get "welcome/index"
  get "welcome/blog"
  get "welcome/blog_single"
  
  get "welcome/cart"
  get "welcome/checkout"
  get "welcome/contact"
  post "welcome/contact_us"

  get "welcome/login"
  get "welcome/order", to: 'welcome#order'
  get "products/show"

  # post 'home/mailchimp', to:'home#mailchimp', as: 'mailchimp'

  get 'welcome/product_details/:id', to: 'welcome#product_details', as: 'product_details'
  post 'welcome/create',to: 'welcome#create'
  get 'welcome/success', to: 'welcome#success', as: "shop_success"
  post 'welcome/create',to: 'welcome#create'

  get "welcome/stripe", to: "welcome#stripe"
  get "welcome/track"
  post "welcome/track"
  get 'welcome/cod'
  get 'welcome/checkout_product', to: "welcome#checkout_product"
  
  post "welcome/cart"
  post "profile/update", to: "profile#update", as: "profile_update"
  get "welcome/myaccount"
  get "welcome/shop"
  get "welcome/error404"
  resources :categories
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  delete 'products/remove_product/:id', to: "products#remove_product", as: "remove_product"

  post '/new/:id', to: "user_wish_list#new", as: "new"
  # delete "user_wish_list/remove_wishlist/:id", to:  "user_wish_list#remove_wishlist", as: "remove_wishlist"
  # get'products/wishlist'

  post 'products/:id/add' => "products#add_quantity", as: "add_quantity"
  post 'products/:id/minus' => "products#dec_quantity", as: "dec_quantity"
  
  # Defines the root path route ("/")
  # root "home#index"
end

app/controllers/wishlist_controller.rb
class WishlistController < ApplicationController
    def index
    @wish = current_user.user_wishlists.all   
        
    end    

    def create
        user_id =  current_user.id
        product = Product.find(params[:id])
        if product.user_wishlists.present? && current_user.user_wishlists.present?
            redirect_to request.referrer, notice: "already in wishlist"   #products_wishlist_path
        else
        wishlist = UserWishlist.create(user_id: user_id , product_id: product.id) 
        if wishlist.save
            redirect_to request.referrer,  notice: "item  added successfully in wishlist"
        end
        end
    end
    
    def destroy
        user_id =  current_user.id
        product = Product.find(params[:id])
        @user_wishlist = UserWishlist.find_by(product_id: product.id)
        if @user_wishlist.destroy
        redirect_to wishlist_index_path, notice: "item successfully removed from wishlist"
        else
        redirect_to wishlist_index_path, notice: "failed to remove from wishilst"
        end
    end       
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/wishlist/index.html.erb
<section class="fix">
<% if @wish.present?%>
	<section id="cart_items">
		<div class="container ">
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Product Image</td>
							<td class="image">Product Name</td>
							<td class="price">Product Price</td>
							<td class="price">Remove from wishlist</td>
						</tr>
					</thead>
          <%# @cart.each do |product| %>
                    <% @wish.each do |wishlist| %>
                        <% product = wishlist.product %>
                        <tbody>
                            <tr>
                            <td class="cart_product">
                                <img src="<%= url_for(product.image) %>"style="height: 80px; width: 70px;">
                            </td>
                            <td class="cart_description">
                                <h3><%= product.name %></h3> 
                            </td>
                            <td class="cart_price">
                                <b>US$ <%= product.price %></b>
                            </td>
                            <td class="cart_price">
                                <%= button_to "X", wishlist_path(product), method: :delete %>
                            </td>
                            </tr>
                        </tbody>
                    <% end %>  
                </table> 
			</div>
		</div>
        <% else %>
	
	</section> <!--/#cart_items-->
    <div style="padding-left: 39%;margin-bottom: 85px;">
	<%= image_tag("home/empty_wishlist.png", alt: "", class: "girl img-responsive") %>
	</div>
<% end %>
</section>