config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  mount RailsAdmin::Engine => '//admin', as: 'rails_admin'
  root 'home#index'
  resources :home, only: [:index] do
    collection do
      post 'mailchimp'
    end
  end

  resources :contact, only: [:index, :create]
  resources :wishlist, only: [:index, :create, :destroy]

  
  get "welcome/index"
  get "welcome/blog"
  get "welcome/blog_single"
  
  get "welcome/cart"
  get "welcome/checkout"
  get "welcome/contact"
  post "welcome/contact_us"

  get "welcome/login"
  get "welcome/order", to: 'welcome#order'
  get "products/show"

  # post 'home/mailchimp', to:'home#mailchimp', as: 'mailchimp'

  get 'welcome/product_details/:id', to: 'welcome#product_details', as: 'product_details'
  post 'welcome/create',to: 'welcome#create'
  get 'welcome/success', to: 'welcome#success', as: "shop_success"
  post 'welcome/create',to: 'welcome#create'

  get "welcome/stripe", to: "welcome#stripe"
  get "welcome/track"
  post "welcome/track"
  get 'welcome/cod'
  get 'welcome/checkout_product', to: "welcome#checkout_product"
  
  post "welcome/cart"
  post "profile/update", to: "profile#update", as: "profile_update"
  get "welcome/myaccount"
  get "welcome/shop"
  get "welcome/error404"
  resources :categories
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  delete 'products/remove_product/:id', to: "products#remove_product", as: "remove_product"

  post '/new/:id', to: "user_wish_list#new", as: "new"
  # delete "user_wish_list/remove_wishlist/:id", to:  "user_wish_list#remove_wishlist", as: "remove_wishlist"
  # get'products/wishlist'

  post 'products/:id/add' => "products#add_quantity", as: "add_quantity"
  post 'products/:id/minus' => "products#dec_quantity", as: "dec_quantity"
  
  # Defines the root path route ("/")
  # root "home#index"
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_categories
    has_many :categories, :through=>:product_categories,:dependent => :destroy
    has_one_attached :image
    has_many :user_wishlists
	has_many :users, through: :user_wishlists
    has_many :order_details, :dependent => :destroy
    has_many :user_orders, through: :order_details, :dependent => :destroy
    validates :quantity, numericality: { greater_than_or_equal_to: 1 , message: "quantity cannot be less than 1"}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def add_to_cart          
    id = params[:id].to_i   #finding product id
    session[:cart] << id unless session[:cart].include?(id)  #adding product to cart unless it is already present in shopping cart
    redirect_to request.referrer, notice: "Product is added to cart"
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    @product = Product.find(params[:id])
    @product.quantity = 1
    @product.save
    redirect_to welcome_cart_path, notice: "Product removed from the cart"
  end

  def index
    @products = Product.all
  end

  def add_quantity
    @item = Product.find(params[:id])
    
      @item.quantity += 1
      @item.save
      respond_to do |format|
      format.js   
      end
  end

  def dec_quantity
    @item = Product.find(params[:id])
    if @item.quantity < 2
      remove_from_cart
    else
      @item.quantity -= 1
      @item.save
      respond_to do |format|
        format.js { render :layout => false }
      end
    end  
  end

  def wishlist 
  end

  def show
    @feature_products = Product.all rescue nil 
    @category = Category.where(parent_id: nil)  
  end  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_quantity.html.erb
<%#= turbo_frame_tag "quantity" do %>
  <%#= binding.pry %>
  <%= product.quantity %>
<%# end %>  

app/views/products/show.html.erb
	
	<section class= "fix">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<% @category.each do |category| %>
						<% subcatagories = category.subcategories%>
						<div class="panel-group category-products" id="accordian" style="margin-top: 30px;"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h6 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#<%= category.id%>">
											<span class="badge pull-right"><i class="fa fa-down"></i></span>
											<h2><%= category.name %></h2>
										</a>
									</h6>
								</div>
							</div>
							<div id="<%= category.id%>" class="panel-collapse collapse">
								<div class="panel-body">
									<% subcatagories.each do |subcat| %>
									<i style="margin-left: 58px;"><%= link_to subcat.name, product_details_path(subcat) %></i>
									<%# <a href=""><%= subcat.subcat_name %>
									<% end %>
								</div>
							</div>
					
						</div><!--/category-products-->	
						<%end%>			
					</div>
				</div>
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Products</h2>
						<% @feature_products.each do |product| %>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<% if product.image.attached? %>
												<img src="<%= url_for(product.image) %> "style="height: 180px; width: 200px;" >
											<% end %>
											<h2>USD $<%= product.price %></h2>
											<p><%= product.name %></p>
											<p><%= product.short_description %></p>
											<p><%= product.long_description %></p>
											<div style="display:flex;">
											
											<div style="margin-left: 32px">
												<%= button_to add_to_cart_path(product) do %>
													<i class="fa fa-shopping-cart" style="font-size:25px"></i>
												<% end %>
											</div>	
											
											<div style="margin-left: 98px;">
												<%= button_to wishlist_index_path(id: product) do %>
													<i class="fa fa-heart-o" style="font-size:25px;color:red"></i>
												<% end %>
											</div>			
											</div>             
										</div>
								</div>
							</div>
						</div>
						<%end%>
					</div><!--features_items-->
				</div>
				</div>
			</div>
		</div>
	</section>
	
	
</body>
</html>

app/views/products/wishlist.html.erb
<section class="fix">
<% if @wish.present?%>

	<section id="cart_items">
		<div class="container fix">
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Product Image</td>
							<td class="image">Product Name</td>
							<td class="price">Product Price</td>
							<td class="price">Remove from wishlist</td>
						</tr>
					</thead>
          <%# @cart.each do |product| %>
          <% @wish.each do |wishlist| %>
            <% product = wishlist.product %>
              <tbody>
                <tr>
                  <td class="cart_product">
                    <img src="<%= url_for(product.image) %>"style="height: 80px; width: 70px;">
                  </td>
                  <td class="cart_description">
                      <h3><%= product.name %></h3> 
                  </td>
                  <td class="cart_price">
                    <b>US$ <%= product.price %></b>
                  </td>
                   <td class="cart_price">
                    <%= button_to "X", remove_wishlist_path(product), method: :delete %>
                  </td>
                </tr>
              </tbody>
          <% end %>  
				</table> 
			</div>
		</div>
	</section> <!--/#cart_items-->
  <% else %>
	<div style="padding-left: 39%;margin-bottom: 85px;">
	<%= image_tag("home/empty_wishlist.png", alt: "", class: "girl img-responsive") %>
	</div>
<% end %>
</section>